### ISSUE TITLE
Instructor Feedback - Project Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [LelinStam/changingIntervals#6]
I know we chatted in person, but I just wanted to document a couple things so I don't lose track of them.

- [x] implement .equals() on your entities and update tests to use .equals() so that all "parts" of the entities are compared in the tests.
- [x] We talked about adding an additional table for workout_type
- [x] Check for and remove all System.out.printlns and printstacktraces. For example: https://github.com/LelinStam/changingIntervals/blob/f346e1815896b59d988659e6f49ec8265232c626/src/Test/java/matc/test/util/Database.java#L42-L47
- [x] Time to implement the generic dao! That should allow you to get rid of all other daos (keep writing dao unit tests for new entities, to verify hibernate is working, though).
- [x] Be sure to check off issue items as you complete them - [x] and close issues when all items are complete.

**Comment by LelinStam** [comment]
I decided against adding an additional table for workout type.
